name: Build on macOS

on:
  push:
    branches-ignore:
      - dependabot/**
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '> 1.15.0'
      - name: Install dependencies
        run: |
          brew update
          brew install curl-openssl
      - name: Run tests
        run: make test
      - name: Build
        run: make kvika
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: kvika
          path: kvika
